"""Public unsubscribe endpoint — CAN-SPAM compliance.

Handles the unsubscribe link generated by EmailSender. No authentication
required because users click this from their email client.
"""

import structlog
from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.models.database import get_db
from apps.api.models.visitor import IdentifiedVisitor
from apps.api.models.visitor_email import VisitorEmail
from apps.api.services.link_decorator import decode_unsubscribe_token

logger = structlog.get_logger()

router = APIRouter(tags=["unsubscribe"])

_SUCCESS_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Unsubscribed</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex; align-items: center; justify-content: center;
      min-height: 100vh; margin: 0; background: #fafafa; color: #333;
    }
    .card {
      text-align: center; padding: 48px 32px; max-width: 420px;
      background: #fff; border-radius: 12px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.08);
    }
    h1 { font-size: 20px; margin-bottom: 8px; }
    p  { font-size: 15px; color: #666; line-height: 1.5; }
  </style>
</head>
<body>
  <div class="card">
    <h1>You've been unsubscribed</h1>
    <p>You will no longer receive emails from us. This may take a moment to propagate.</p>
  </div>
</body>
</html>
"""


@router.get("/unsubscribe", response_class=HTMLResponse)
async def unsubscribe(
    t: str = Query(..., description="Signed unsubscribe token"),
    db: AsyncSession = Depends(get_db),
) -> HTMLResponse:
    """Mark a visitor as do-not-email.

    The email is recovered from the signed token `t` — never from a raw
    query param — so a caller cannot suppress an address they don't own.
    Always returns the success page regardless of whether the token is valid
    or the email exists, so we never leak token/email-existence information.
    """
    email = decode_unsubscribe_token(t)
    if not email:
        # Invalid/forged/expired token: do nothing, but return the same
        # generic success page so we don't reveal that the token was bad.
        logger.info("unsubscribe_invalid_token")
        return HTMLResponse(content=_SUCCESS_HTML)

    email_lower = email.strip().lower()

    try:
        # 1. Check identified_visitors table (email is a direct column)
        result = await db.execute(
            select(IdentifiedVisitor).where(
                IdentifiedVisitor.email == email_lower,
            )
        )
        visitors = result.scalars().all()

        if visitors:
            for visitor in visitors:
                visitor.do_not_email = True
            await db.commit()
            logger.info(
                "unsubscribe_ok",
                email_domain=email_lower.split("@")[-1],
                count=len(visitors),
            )
        else:
            # 2. Check visitor_emails table (emails may be in a related table)
            ve_result = await db.execute(
                select(VisitorEmail).where(
                    VisitorEmail.email == email_lower,
                )
            )
            visitor_emails = ve_result.scalars().all()

            if visitor_emails:
                # Find the corresponding IdentifiedVisitor rows by visitor_id + site_id
                for ve in visitor_emails:
                    iv_result = await db.execute(
                        select(IdentifiedVisitor).where(
                            IdentifiedVisitor.visitor_id == ve.visitor_id,
                            IdentifiedVisitor.site_id == ve.site_id,
                        )
                    )
                    iv = iv_result.scalar_one_or_none()
                    if iv:
                        iv.do_not_email = True

                await db.commit()
                logger.info(
                    "unsubscribe_via_visitor_emails",
                    email_domain=email_lower.split("@")[-1],
                    count=len(visitor_emails),
                )
            else:
                logger.info(
                    "unsubscribe_email_not_found",
                    email_domain=email_lower.split("@")[-1],
                )
    except Exception:
        logger.exception("unsubscribe_error")
        # Swallow the error — still show success page to the user
        await db.rollback()

    return HTMLResponse(content=_SUCCESS_HTML)
