"""baseline schema

Revision ID: cd811a8b1f32
Revises: 
Create Date: 2026-06-13 19:53:56.487821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd811a8b1f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beam_identity_graph',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_site_id', sa.String(length=50), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_beam_identity_fingerprint', 'beam_identity_graph', ['fingerprint'], unique=False)
    op.create_index('uq_beam_identity_fp_email', 'beam_identity_graph', ['fingerprint', 'email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('employee_count', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('total_visitors', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_pageviews', sa.Integer(), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_site_intent', 'companies', ['site_id', 'intent_score'], unique=False)
    op.create_index('uq_companies_site_domain', 'companies', ['site_id', 'domain'], unique=True)
    op.create_table('enrichment_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('personal_website', sa.String(length=500), nullable=True),
    sa.Column('linkedin_headline', sa.String(length=500), nullable=True),
    sa.Column('linkedin_summary', sa.Text(), nullable=True),
    sa.Column('linkedin_follower_count', sa.Integer(), nullable=True),
    sa.Column('twitter_bio', sa.String(length=500), nullable=True),
    sa.Column('twitter_follower_count', sa.Integer(), nullable=True),
    sa.Column('twitter_recent_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('social_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social_context_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_completeness', sa.Float(), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_enrichment_site_visitor', 'enrichment_profiles', ['site_id', 'visitor_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser_lang', sa.String(length=20), nullable=True),
    sa.Column('scroll_depth', sa.Integer(), nullable=True),
    sa.Column('time_on_page', sa.Integer(), nullable=True),
    sa.Column('element_text', sa.String(length=500), nullable=True),
    sa.Column('element_href', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('page_path', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_site_created', 'events', ['site_id', 'created_at'], unique=False)
    op.create_index('ix_events_site_visitor', 'events', ['site_id', 'visitor_id'], unique=False)
    op.create_index('uq_events_event_id', 'events', ['event_id'], unique=True)
    op.create_table('feature_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identified_visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('resolution_provider', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('do_not_email', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_identified_site_visitor', 'identified_visitors', ['site_id', 'visitor_id'], unique=True)
    op.create_table('resolution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resolution_logs_site_created', 'resolution_logs', ['site_id', 'created_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('messaging_angle', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segments_site', 'segments', ['site_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('detected_platform', sa.String(length=50), nullable=True),
    sa.Column('pixel_verified', sa.Boolean(), nullable=False),
    sa.Column('daily_resolution_budget', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id')
    )
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=20), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('tone_preference', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_identified_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('billing_cycle_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('visitor_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'visitor_id', 'email', name='uq_visitor_email_site_vid_email')
    )
    op.create_index('idx_visitor_emails_email', 'visitor_emails', ['email'], unique=False)
    op.create_index('idx_visitor_emails_site_visitor', 'visitor_emails', ['site_id', 'visitor_id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('total_pageviews', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('avg_time_on_page', sa.Float(), nullable=False),
    sa.Column('max_scroll_depth', sa.Integer(), nullable=False),
    sa.Column('pages_visited', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_referrer', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('company_domain', sa.String(length=253), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('canonical_visitor_id', sa.String(length=100), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('identity_status', sa.String(length=30), nullable=False),
    sa.Column('enrichment_status', sa.String(length=20), nullable=False),
    sa.Column('segmented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visitors_identity_status', 'visitors', ['site_id', 'identity_status'], unique=False)
    op.create_index('idx_visitors_site_enrichment', 'visitors', ['site_id', 'enrichment_status'], unique=False)
    op.create_index('idx_visitors_site_intent', 'visitors', ['site_id', 'intent_score'], unique=False)
    op.create_index('uq_visitors_site_visitor', 'visitors', ['site_id', 'visitor_id'], unique=True)
    op.create_table('waitlist_signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('site_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog_posts',
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.Text(), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_scheduled_for'), 'blog_posts', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_blog_posts_site_id'), 'blog_posts', ['site_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_status'), 'blog_posts', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_site', 'campaigns', ['site_id'], unique=False)
    op.create_table('feature_request_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_request_id'], ['feature_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_request_id', 'user_id', name='uq_feature_vote_user')
    )
    op.create_table('segment_members',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'visitor_id', 'id')
    )
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', name='platform'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_examples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', name='platform'), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('ai_draft', sa.Text(), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.Enum('approved', 'edited', 'rejected', name='feedbacktype'), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_touchpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('touchpoint_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_touchpoints_campaign', 'campaign_touchpoints', ['campaign_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', name='platform'), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_username', sa.String(length=255), nullable=False),
    sa.Column('sender_avatar_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('replied', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_platform_message_id'), 'messages', ['platform_message_id'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', name='platform'), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_username', sa.String(length=255), nullable=False),
    sa.Column('author_avatar_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('commented', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_posts_account_posted', 'posts', ['social_account_id', 'posted_at'], unique=False)
    op.create_index(op.f('ix_posts_platform_post_id'), 'posts', ['platform_post_id'], unique=True)
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('reply', 'comment', name='drafttype'), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'twitter', 'tiktok', name='platform'), nullable=False),
    sa.Column('ai_content', sa.Text(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'sent', 'failed', name='draftstatus'), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=True),
    sa.Column('context_summary', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_attributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('engagement_type', sa.String(length=20), nullable=False),
    sa.Column('target_post_url', sa.String(length=2000), nullable=True),
    sa.Column('utm_tag', sa.String(length=100), nullable=False),
    sa.Column('new_visitors_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_identified_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('engaged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_attributions_site_id'), 'engagement_attributions', ['site_id'], unique=False)
    op.create_index(op.f('ix_engagement_attributions_utm_tag'), 'engagement_attributions', ['utm_tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engagement_attributions_utm_tag'), table_name='engagement_attributions')
    op.drop_index(op.f('ix_engagement_attributions_site_id'), table_name='engagement_attributions')
    op.drop_table('engagement_attributions')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_posts_platform_post_id'), table_name='posts')
    op.drop_index('idx_posts_account_posted', table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_messages_platform_message_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_campaign_touchpoints_campaign', table_name='campaign_touchpoints')
    op.drop_table('campaign_touchpoints')
    op.drop_table('voice_examples')
    op.drop_table('social_accounts')
    op.drop_table('segment_members')
    op.drop_table('feature_request_votes')
    op.drop_index('idx_campaigns_site', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_blog_posts_status'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_site_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_scheduled_for'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('waitlist_signups')
    op.drop_index('uq_visitors_site_visitor', table_name='visitors')
    op.drop_index('idx_visitors_site_intent', table_name='visitors')
    op.drop_index('idx_visitors_site_enrichment', table_name='visitors')
    op.drop_index('idx_visitors_identity_status', table_name='visitors')
    op.drop_table('visitors')
    op.drop_index('idx_visitor_emails_site_visitor', table_name='visitor_emails')
    op.drop_index('idx_visitor_emails_email', table_name='visitor_emails')
    op.drop_table('visitor_emails')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_api_keys')
    op.drop_table('stripe_events')
    op.drop_table('sites')
    op.drop_index('idx_segments_site', table_name='segments')
    op.drop_table('segments')
    op.drop_index('idx_resolution_logs_site_created', table_name='resolution_logs')
    op.drop_table('resolution_logs')
    op.drop_index('uq_identified_site_visitor', table_name='identified_visitors')
    op.drop_table('identified_visitors')
    op.drop_table('feature_requests')
    op.drop_index('uq_events_event_id', table_name='events')
    op.drop_index('ix_events_site_visitor', table_name='events')
    op.drop_index('ix_events_site_created', table_name='events')
    op.drop_index('ix_events_created', table_name='events')
    op.drop_table('events')
    op.drop_index('uq_enrichment_site_visitor', table_name='enrichment_profiles')
    op.drop_table('enrichment_profiles')
    op.drop_index('uq_companies_site_domain', table_name='companies')
    op.drop_index('ix_companies_site_intent', table_name='companies')
    op.drop_table('companies')
    op.drop_index('uq_beam_identity_fp_email', table_name='beam_identity_graph')
    op.drop_index('idx_beam_identity_fingerprint', table_name='beam_identity_graph')
    op.drop_table('beam_identity_graph')
    # ### end Alembic commands ###
